-keep class com.katsuyamaki.DroidOSFOSSLauncher.ShellUserService { *; }
-keep class com.katsuyamaki.DroidOSFOSSLauncher.IShellService { *; }
-keep interface com.katsuyamaki.DroidOSFOSSLauncher.IShellService { *; }
