-keep class com.katsuyamaki.DroidOSLauncher.ShellUserService { *; }
-keep class com.katsuyamaki.DroidOSLauncher.IShellService { *; }
-keep interface com.katsuyamaki.DroidOSLauncher.IShellService { *; }
